name: CI
on:
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests and coverage
        run: |
          export PRIVATE_KEY="0000000000000000000000000000000000000000000000000000000000000001"
          yarn install
          yarn test
          yarn coverage
      - name: Post coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
