name: CI
on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Compile test
        run: yarn hh:compile

      - name: Run unit tests and coverage
        run: |
          export PRIVATE_KEY="0000000000000000000000000000000000000000000000000000000000000001"
          yarn test
          yarn coverage
